# yaml-language-server: $schema=https://raw.githubusercontent.com/Seelen-Inc/slu-lib/refs/heads/master/gen/schemas/theme.schema.json
id: "@eythaann/variables-test"
metadata:
  displayName: Variables Test
  description: this theme is just for testing
  tags: ['weg']
settings:
  - syntax: <color>
    name: --testing-settings
    label: Testing Color Setting
    initialValue: '#f00'
  - syntax: <color>
    name: --testing-settings2
    label: Testing Color Setting 2
    initialValue: '#00f'
  - syntax: <length>
    name: --testing-sizes
    label: Testing Length Setting 3
    initialValue: 20
    initialValueUnit: px
  - syntax: <number>
    name: --testing-number
    label: Testing Number Setting
    initialValue: 60
  - syntax: <string>
    name: --testing-string
    label: Testing User Input
    initialValue: 'hello world'
  - syntax: <url>
    name: --testing-url
    label: Testing User URL Input
    initialValue: https://google.com